[env:rak4631_rui]
platform = https://github.com/RAKWireless/RAKwireless-Arduino-BSP-Index/raw/main/package_rakwireless_com_rui_index.json
board = rak4631_rui
framework = arduino
lib_deps =
    4-20ma/ModbusMaster
upload_protocol = nrfjprog
monitor_speed = 115200
